// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import ExplorerController from "./explorer_controller"
application.register("explorer", ExplorerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SearchFormController from "./search_form_controller"
application.register("search-form", SearchFormController)

import TicketsFilterController from "./tickets_filter_controller"
application.register("tickets-filter", TicketsFilterController)

import WalletController from "./wallet_controller"
application.register("wallet", WalletController)
